# Generated by Django 3.2.8 on 2022-08-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_question_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
