# Generated by Django 3.2.8 on 2022-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_question_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
