# Generated by Django 3.2.8 on 2022-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
